repellency:
  method: kernel_fast
  n_embed: 4
  guidance_scale : 0.0
  params:
    sigma : 2.75
    scale: 0.03
    proj_ref_path : "caches/sdv3/i2p_sexual/repellency_proj_ref.pt"
    cache_proj_ref : True
    # proj_noisy_ref_path_for_beta : "caches/sd/i2p/repellency_noisy_proj_ref_for_beta.pt"
    # cache_noisy_ref_path_for_beta : False
    # beta_threshold : 1.0e-9
    # beta_threshold_margin : 0.0 # >= 0.0

# repellency dataset
data:
  name: nudity
  root: datasets/nudity
  class_info : i2p_sexual

# pred_xstart
mean_processor:
  dynamic_threshold: False
  clip_denoised: True