batch_size: 1
category: coco
clip_model: ViT-H-14
clip_pretrain: laion2b_s32b_b79k
config: configs/sld_rep_config.json
data: datasets/nudity-ring-a-bell.csv
device: cuda:0
erase_concept_checkpoint: null
erase_id: sld_rep
eval_step: 50
every_k: 3
freeu_hyp: 1.0-1.0-0.9-0.2
guidance_scale: 7.5
image_length: 512
iter: 3000
latent_re_attention: false
loss_weight: 1.0
lr: 0.1
max_length: 77
model_id: CompVis/stable-diffusion-v1-4
negative_prompts: null
nudenet_path: pretrained/classifier_model.onnx
nudity_thr: 0.6
num_images_per_prompt: 1
num_inference_steps: 50
num_samples: 1
print_step: 100
prompt_bs: 1
prompt_len: 16
q16_path: ./pretrained/Q16_prompts.p
re_attn_t: -1,1001
safe_level: WEAK
safree: false
save_dir: results/sld_weak_000005_rep_SD_CompVis/stable-diffusion-v1-4-coco
seed: null
self_validation_filter: false
sf_alpha: 0.01
target_prompts: null
task_config: configs/data_negation/dev_250107/repellency_config_sd_250107.yaml
up_t: 10
valid_case_numbers: 0, 100000
weight_decay: 0.1
